apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: <RoleBinding name>
  namespace: <namespcae>

roleRef:
  kind: ClusterRole
  name: <ClusterRole name>
  apiGroup: rbac.authorization.k8s.io
  
subjects:
- kind: User
  name: <User name>
  apiGroup: rbac.authorization.k8s.io

- kind: ServiceAccount
  name: <ServiceAccout name>
  namespace: <namespcae>

- kind: Group
  name: <Group name>
  apiGroup: rbac.authorization.k8s.io