apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: <EKS Cluster name>
  version: "<EKS version>"
  region: <region>

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

iamIdentityMappings:
  - arn: arn:aws:iam::<Account ID>:role/<Role name>
    groups:
      - system:masters
    username: admin
    noDuplicateARNs: true

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true
  - metadata:
      name: cert-manager
      namespace: cert-manager
    wellKnownPolicies:
      certManager: true

vpc:
  subnets:
    public:
      <region>a: { id: public_a }
      <region>b: { id: public_b }
      <region>c: { id: public_c }
    private:
      <region>a: { id: private_a }
      <region>b: { id: private_b }
      <region>c: { id: private_c }

fargateProfiles:
  - name: <fargate profile name>
    selectors:
      - namespace: default
      - namespace: kube-system
      - namespace: cert-manager
  - name: <fargate name>
    selectors:
      - namespace: <namespace>
        labels:
          <key>: <value>