apiVersion: v1
kind: Service
metadata:
  name: <service name>
  namespace: <namespace>
  annotations:
    <key>: <value>
spec:
  selector:
    <key>: <value> 
  ports:
    - protocol: TCP
      port: <port>
      targetPort: <port>
  type: LoadBalancer