apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
  namespace: <Namespace>
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "ebs-sc"
  resources:
    requests:
      storage: 4Gi