apiVersion: application-networking.k8s.aws/v1alpha1
kind: IAMAuthPolicy
metadata:
    name: iam-auth-policy
    namespace: default
spec:
    targetRef:
        group: "gateway.networking.k8s.io"
        kind: HTTPRoute
        name: lattice-svc
        namespace: default
    policy: |
        {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Effect": "Allow",
                    "Principal": "*",
                    "Action": "*",
                    "Resource": "*",
                    "Condition": {
                        "IpAddress": {
                            "aws:SourceIp": "BASTION/32"
                        }
                    }
                }
            ]
        }