apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-sidecar
  namespace: wsi-ns
  labels:
    app.kubernetes.io/name: fluent-bit-sidecar
    helm.sh/chart: default-0.1.0
    app.kubernetes.io/instance: flb-sidecar
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf

    [INPUT]
        Name          tail
        Path          /logs/app.log
        Parser        custom_log
        Tag           app.log
  
    [OUTPUT]
        Name          stdout
        Match         *

    [OUTPUT]
        Name          cloudwatch
        Match         *
        endpoint      https://logs.ap-northeast-2.amazonaws.com
        region        ap-northeast-2
        log_group_name <CloudWatch_Log_Group_Name>
        log_stream_name log-${HOSTNAME}
        auto_create_group true

  parsers.conf: |
    [PARSER]
        Name           custom_log
        Format         regex
        Regex          ^(?<year>\d{4})-(?<month>\d{2})-(?<day>\d{2})\s(?<hour>\d{2}):(?<minute>\d{2}):(?<second>\d{2}),\d+ - - (?<ip>\d+\.\d+\.\d+\.\d+) (?<port>\d+) (?<method>\S+) (?<path>\S+) (?<statuscode>\d+)$
        Time_Key       time
        Time_Format    %Y-%m-%d %H:%M:%S
        Time_Keep      On