apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets
  namespace: demo
spec:
  provider:
    aws:
      service: SecretsManager
      region: REGION_CODE
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-cert-controller