{
  "installCRDs": true,
  "nodeSelector": {
    "type": "addon"
  },
  "webhook": {
    "nodeSelector": {
      "type": "addon"
    }
  },
  "certController": {
    "nodeSelector": {
      "type": "addon"
    }
  }
}