apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: kube-system-ns-exclude-config
  namespace: gatekeeper-system
spec:
  match:
    - excludedNamespaces: ["kube-system"]
      processes: ["*"]